---
{
  pipeline: [
    # "ae1",
    # "ae2",
    "ae3",
    "ae4",
    "mlp",
  ],
  config: {
    common: {
      train_data_source: '{data_path}/corr/corr_1D_cv_{fold}_train.csv',
      valid_data_source: '{data_path}/corr/corr_1D_cv_{fold}_valid.csv',
      test_data_source: '{data_path}/corr/corr_1D_cv_{fold}_test.csv',
      log_file: '{log_path}/{namespace}.{step}.cv_{fold}.csv',
      data_transform_1: "{result_path}/{namespace}.ae1_cv_{fold}.pkl",
      data_transform_2: "{result_path}/{namespace}.ae2_cv_{fold}.pkl",
      data_transform_3: "{result_path}/{namespace}.ae3_cv_{fold}.pkl",
      data_transform_4: "{result_path}/{namespace}.ae4_cv_{fold}.pkl",
      save_path: "{result_path}/{namespace}.{step}_cv_{fold}.pkl",
    },
    ae1: {
      layer_in: 19900,
      layer_out: 15000,
      irange: 0.013111818, # sqrt(6/(fan in + fan out))
      layer_enc: tanh,
      layer_dec: "null",
      layer_batch: 100,
      layer_max_epochs: 8000,
      corruption: 0.6,
    },
    ae2: {
      layer_in: 15000,
      layer_out: 10000,
      irange: 0.015491933,
      layer_enc: tanh,
      layer_dec: "null",
      layer_batch: 100,
      layer_max_epochs: 6000,
      corruption: 0.7,
    },
    ae3: {
      layer_in: 10000,
      layer_out: 5000,
      irange: 0.02,
      layer_enc: tanh,
      layer_dec: "null",
      layer_batch: 100,
      layer_max_epochs: 4000,
      corruption: 0.8,
    },
    ae4: {
      layer_in: 5000,
      layer_out: 500,
      irange: 0.033028913,
      layer_enc: tanh,
      layer_dec: "null",
      layer_batch: 100,
      layer_max_epochs: 2000,
      corruption: 0.9,
    },
    mlp: {
      layer_in: 19900,
      layer_max_epochs: 100,
      layer_batch: 10,
    },
  }
}
