---
{
  pipeline: [
    # "ae1",
    # "ae2",
    # "ae3",
    "mlp",
  ],
  config: {
    common: {
      data_source: "{data_path}/corr/corr-norm_cv_{fold}_train.csv",
      test_data_source: "{data_path}/corr/corr-norm_cv_{fold}_test.csv",
      log_file: "{log_path}/{namespace}.{step}.cv_{fold}.csv",
      data_train_start: 0,
      data_train_stop: 900,
      data_valid_start: 900,
      data_valid_stop: 930,
      data_transform_1: "{result_path}/{namespace}.ae1_cv_{fold}.pkl",
      data_transform_2: "{result_path}/{namespace}.ae2_cv_{fold}.pkl",
      data_transform_3: "{result_path}/{namespace}.ae3_cv_{fold}.pkl",
      data_transform_4: "{result_path}/{namespace}.ae4_cv_{fold}.pkl",
      save_path: "{result_path}/{namespace}.{step}_cv_{fold}.pkl",
    },
    ae1: {
      layer_in: 17955,
      layer_out: 10000,
      layer_enc: tanh,
      layer_dec: "null",
      layer_batch: 100,
      layer_max_epochs: 100,
      corruption: 0.2,
    },
    ae2: {
      layer_in: 10000,
      layer_out: 1000,
      layer_enc: tanh,
      layer_dec: "null",
      layer_batch: 100,
      layer_max_epochs: 100,
      corruption: 0.3,
    },
    ae3: {
      layer_in: 1000,
      layer_out: 1000,
      layer_enc: tanh,
      layer_dec: "null",
      layer_batch: 100,
      layer_max_epochs: 100,
      corruption: 0.5,
    },
    mlp: {
      layer_in: 17955,
      layer_max_epochs: 100,
      layer_batch: 10,
    },
  }
}