---
{
  pipeline: [
    # 'ae-1',
    # 'ae-2',
    'mlp',
  ],
  config: {
    common: {
      data_source: '{data_path}/corr/corr_cv_{fold}_train.csv',
      test_data_source: '{data_path}/corr/corr_cv_{fold}_test.csv',
      log_file: '{log_path}/{namespace}.{step}.cv_{fold}.csv',
      data_train_start: 0,
      data_train_stop: 900,
      data_valid_start: 900,
      data_valid_stop: 930,
      data_transform_1: '{result_path}/{namespace}.ae-1_cv_{fold}.pkl',
      data_transform_2: '{result_path}/{namespace}.ae-2_cv_{fold}.pkl',
    },
    ae-1: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 17955,
      layer_out: 1000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 50,
      corruption: 0.2,
    },
    ae-2: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 1000,
      layer_out: 1000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 50,
      corruption: 0.5,
    },
    mlp: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 17955,
      layer_max_epochs: 30,
      layer_batch: 10,
    },
  }
}