---
{
  pipeline: [
    'pre-autoencoder-1',
    'pre-autoencoder-2',
    'mlp'
  ],
  config: {
    common: {
      data_source: '%(data_path)s/corr_%(fold)s_train.csv',
      data_train_start: 0,
      data_train_stop: 900,
      data_valid_start: 900,
      data_valid_stop: 931,
    },
    pre-autoencoder-1: {
      save_path: '%(result_path)s/%(namespace)s.%(step)s.%(fold)s.pkl',
      layer_in: 17955,
      layer_out: 1000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 400,
    },
    pre-autoencoder-2: {
      data_transform: '%(result_path)s/%(namespace)s.pre-autoencoder-1.%(fold)s.pkl',
      save_path: '%(result_path)s/%(namespace)s.%(step)s.%(fold)s.pkl',
      layer_in: 1000,
      layer_out: 1000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 400,
    },
    mlp: {
      layer_max_epochs: 50,
      layer_1: '%(result_path)s/%(namespace)s.pre-autoencoder-1.%(fold)s.pkl',
      layer_2: '%(result_path)s/%(namespace)s.pre-autoencoder-2.%(fold)s.pkl',
      save_path: '%(result_path)s/%(namespace)s.%(step)s.%(fold)s.pkl',
    },
  }
}
