!obj:pylearn2.train.Train {

    dataset: &train !obj:csv_dataset.CSVDataset {
        path: '{train_data_source}',
        expect_headers: False,
        expect_labels: True,
    },

    model: !obj:pylearn2.models.mlp.MLP {
        nvis: {layer_in},
        layers: [
            !obj:pretrained.PretrainedLayer {
                layer_name: 'h1',
                layer_content: !pkl: {data_transform_1},
            },
            !obj:pretrained.PretrainedLayer {
                layer_name: 'h2',
                layer_content: !pkl: {data_transform_2},
            },
            !obj:pretrained.PretrainedLayer {
                layer_name: 'h3',
                layer_content: !pkl: {data_transform_3},
            },
            !obj:pylearn2.models.mlp.Softmax {
                irange: .005,
                layer_name: 'y',
                n_classes: 2,
            },
        ],
    },

    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: .00001,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.AdaGrad {},
        batch_size: {layer_batch},
        train_iteration_mode: even_shuffled_sequential,
        monitor_iteration_mode: even_shuffled_sequential,
        monitoring_dataset: {
            'train': *train,
            'valid': !obj:csv_dataset.CSVDataset {
                path: '{valid_data_source}',
                expect_headers: False,
                expect_labels: True,
            },
            'test': !obj:csv_dataset.CSVDataset {
                path: '{test_data_source}',
                expect_headers: False,
                expect_labels: True,
            },
        },
        # cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
        #     # default_input_include_prob: 1.0,
        #     # default_input_scale: 1.0,
        #     input_include_probs: {
        #         'h1': 0.8,
        #         'h2': 0.8,
        #         'h3': 0.8,
        #     },
        #     input_scales: {
        #         'h1': 1.25,
        #         'h2': 1.25,
        #         'h3': 1.25,
        #     },
        #     per_example: True,
        # },
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: {layer_max_epochs},
        },
    },

    extensions: [
        !obj:best_params.MonitorBasedSaveBest {
            channel_name: "valid_y_misclass",
            save_path: "{save_path}",
        },
        !obj:csv_monitoring.CSVMonitoring {
            name: "{namespace}.{step}.cv_{fold}",
            file: {log_file},
        },
    ],

}
