!obj:pylearn2.train.Train {

    dataset: &train !obj:pylearn2.datasets.csv_dataset.CSVDataset {
        path: '{data_source}',
        expect_headers: False,
        expect_labels: True,
        start: {data_train_start},
        stop: {data_train_stop},
    },

    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: {layer_batch},
        nvis: 17955,
        layers: [
            !obj:pylearn2.models.mlp.PretrainedLayer {
                layer_name: 'h1',
                layer_content: !pkl: {data_transform_1},
            },
            !obj:pylearn2.models.mlp.PretrainedLayer {
                layer_name: 'h2',
                layer_content: !pkl: {data_transform_2},
            },
            !obj:pylearn2.models.mlp.Softmax {
                max_col_norm: 2,
                layer_name: 'y',
                n_classes: 2,
                irange: .05,
            },
        ],
    },

    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: .02,
        monitoring_dataset: {
            'train': *train,
            'valid': !obj:pylearn2.datasets.csv_dataset.CSVDataset {
                path: '{data_source}',
                expect_headers: False,
                expect_labels: True,
                start: {data_valid_start},
                stop: {data_valid_stop},
            },
            'test': !obj:pylearn2.datasets.csv_dataset.CSVDataset {
                path: '{test_data_source}',
                expect_headers: False,
                expect_labels: True,
                start: 0,
                stop: 100,
            },
        },
        cost: !obj:pylearn2.costs.mlp.Default {},
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: {layer_max_epochs},
        },
    },

    extensions: [
        !obj:pylearn2.training_algorithms.sgd.MonitorBasedLRAdjuster {
             dataset_name: 'valid',
             high_trigger: 1.75,
             shrink_amt: .99,
             low_trigger: .99,
             grow_amt: 1.01
        },
        !obj:best_params.MonitorBasedSaveBest {
             channel_name: "valid_y_misclass",
             save_path: "{save_path}",
        },
        !obj:csv_monitoring.CSVMonitoring {
            name: "{namespace}.{step}.cv_{fold}",
            file: {log_file},
        },
    ],

}
