!obj:pylearn2.train.Train {

    dataset: &train !obj:csv_dataset.CSVDataset {
        path: '{train_data_source}',
        expect_headers: False,
        expect_labels: True,
    },

    model: !obj:pylearn2.models.autoencoder.DenoisingAutoencoder {
        nvis: {layer_in},
        nhid: {layer_out},
        irange: 0.01416576493,
        corruptor: !obj:pylearn2.corruption.BinomialCorruptor {
            corruption_level: {corruption},
        },
        tied_weights: True,
        act_enc: {layer_enc},
        act_dec: {layer_dec},
    },

    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate : 0.0001,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.AdaGrad {},
        batch_size : {layer_batch},
        monitoring_dataset: {
            'train': *train,
            'valid': !obj:csv_dataset.CSVDataset {
                path: '{valid_data_source}',
                expect_headers: False,
                expect_labels: True,
            },
            'test': !obj:csv_dataset.CSVDataset {
                path: '{test_data_source}',
                expect_headers: False,
                expect_labels: True,
            },
        },
        cost: !obj:pylearn2.costs.autoencoder.MeanSquaredReconstructionError {},
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: {layer_max_epochs},
        }
    },

    extensions: [
        !obj:best_params.MonitorBasedSaveBest {
            channel_name: "valid_objective",
            save_path: "{save_path}",
        },
        !obj:csv_monitoring.CSVMonitoring {
            name: "{namespace}.{step}.cv_{fold}",
            file: {log_file}
        },
    ],

}
