---
{
  pipeline: [
    # 'pre-autoencoder-1-valid',
    # 'pre-autoencoder-2-valid',
    # 'pre-autoencoder-3-valid',
    'mlp-ada',
  ],
  config: {
    common: {
      train_data_source: '{data_path}/corr/corr_1D_cv_{fold}_train.csv',
      valid_data_source: '{data_path}/corr/corr_1D_cv_{fold}_valid.csv',
      test_data_source: '{data_path}/corr/corr_1D_cv_{fold}_test.csv',
      log_file: '{log_path}/{namespace}.{step}.cv_{fold}.csv',
      data_transform_1: '{result_path}/{namespace}.pre-autoencoder-1-valid_cv_{fold}.pkl',
      data_transform_2: '{result_path}/{namespace}.pre-autoencoder-2-valid_cv_{fold}.pkl',
      data_transform_3: '{result_path}/{namespace}.pre-autoencoder-3-valid_cv_{fold}.pkl',
    },
    pre-autoencoder-1-valid: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 19900,
      layer_out: 10000,
      layer_batch: 40,
      layer_max_epochs: 1000,
      corruption: 0.4,
      layer_enc: 'tanh',
      layer_dec: 'null',
    },
    pre-autoencoder-2-valid: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 10000,
      layer_out: 1000,
      layer_batch: 40,
      layer_max_epochs: 1000,
      corruption: 0.5,
      layer_enc: 'tanh',
      layer_dec: 'null',
    },
    pre-autoencoder-3-valid: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 1000,
      layer_out: 40,
      layer_batch: 100,
      layer_max_epochs: 1000,
      corruption: 0.6,
      layer_enc: 'tanh',
      layer_dec: 'null',
    },
    mlp-ada: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 19900,
      layer_max_epochs: 400,
      layer_batch: 40,
    },
  }
}
