---
{
  pipeline: [
    # 'pre-autoencoder-1-valid',
    'pre-autoencoder-1-mlp-valid',
  ],
  config: {
    common: {
      data_source: '{data_path}/corr/corr_cv_{fold}_train.csv',
      test_data_source: '{data_path}/corr/corr_cv_{fold}_test.csv',
      log_file: '{log_path}/{namespace}.{step}.cv_{fold}.csv',
      data_train_start: 0,
      data_train_stop: 900,
      data_valid_start: 900,
      data_valid_stop: 930,
      data_transform_1: '{result_path}/{namespace}.pre-autoencoder-1-valid_cv_{fold}.pkl',
    },
    pre-autoencoder-1-valid: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 17955,
      layer_out: 6000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 600,
      corruption: 0.3,
    },
    mlp-one-valid: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_max_epochs: 200,
      layer_batch: 100,
    },
  }
}