!obj:pylearn2.train.Train {

    dataset: &train !obj:pylearn2.datasets.transformer_dataset.TransformerDataset {
        raw: !obj:pylearn2.datasets.csv_dataset.CSVDataset {
            path: '{data_source}',
            expect_headers: False,
            expect_labels: True,
            start: {data_train_start},
            stop: {data_train_stop}
        },
        transformer: !pkl: {data_transform_1}
    },

    model: !obj:pylearn2.models.autoencoder.DenoisingAutoencoder {
        nvis : {layer_in},
        nhid : {layer_out},
        irange : 0.05,
        corruptor: !obj:pylearn2.corruption.BinomialCorruptor {
            corruption_level: {corruption},
        },
        act_enc: {layer_enc},
        act_dec: {layer_dec},
    },

    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate : 1e-3,
        batch_size : {layer_batch},
        monitoring_dataset : *train,
        cost : !obj:pylearn2.costs.autoencoder.MeanSquaredReconstructionError {},
        termination_criterion : !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: {layer_max_epochs},
        }
    },

    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'objective',
             save_path: "{save_path}",
        },
        !obj:csv_monitoring.CSVMonitoring {
            name: "Fold {fold}",
            file: {log_file},
        },
    ],

}
