---
{
  pipeline: [
    'autoencoder',
    'mlp',
  ],
  config: {
    common: {
      data_source: '{data_path}/corr/corr_cv_{fold}_train.csv',
      test_data_source: '{data_path}/corr/corr_cv_{fold}_test.csv',
      log_file: '{log_path}/fine-tunned/{namespace}.{step}.cv_{fold}.csv',
      data_train_start: 0,
      data_train_stop: 900,
      data_valid_start: 900,
      data_valid_stop: 930,
      data_transform: '{result_path}/fine-tunned/{namespace}.autoencoder_cv_{fold}.pkl',
      layer_in: 17955,
    },
    autoencoder: {
      save_path: '{result_path}/fine-tunned/{namespace}.{step}_cv_{fold}.pkl',
      layer_out: 6000,
      layer_enc: sigmoid,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 600,
      corruption: 0.3,
    },
    mlp: {
      save_path: '{result_path}/fine-tunned/{namespace}.{step}_cv_{fold}.pkl',
      layer_max_epochs: 200,
      layer_batch: 100,
    },
  }
}