!obj:pylearn2.models.mlp.MLP {
    batch_size: 10,
    nvis: 19900,
    layers: [
        !obj:pretrained.PretrainedLayer {
            layer_name: "h1",
            layer_content: !pkl: /home/anibal.heinsfeld/repos/acerta-abide/experiments/deep.valid/1/models/deep.valid.ae1_cv_1.pkl,
        },
        !obj:pretrained.PretrainedLayer {
            layer_name: "h2",
            layer_content: !pkl: /home/anibal.heinsfeld/repos/acerta-abide/experiments/deep.valid/1/models/deep.valid.ae2_cv_1.pkl,
        },
        !obj:pretrained.PretrainedLayer {
            layer_name: "h3",
            layer_content: !pkl: /home/anibal.heinsfeld/repos/acerta-abide/experiments/deep.valid/1/models/deep.valid.ae3_cv_1.pkl,
        },
        !obj:pylearn2.models.mlp.Softmax {
            max_col_norm: 3.0,
            layer_name: "y",
            n_classes: 2,
            irange: 0.05,
        },
    ],
}