---
{
  pipeline: [
    'mlp',
  ],
  config: {
    common: {
      train_data_source: '{data_path}/corr/corr_1D_cv_{fold}_train.csv',
      valid_data_source: '{data_path}/corr/corr_1D_cv_{fold}_valid.csv',
      test_data_source: '{data_path}/corr/corr_1D_cv_{fold}_test.csv',
      log_file: '{log_path}/{namespace}.{step}.cv_{fold}.csv',
    },
    mlp: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 19900,
      layer_max_epochs: 100,
      layer_batch: 10,
    },
  }
}
