!obj:pylearn2.cross_validation.TrainCV {

    dataset_iterator: !obj:pylearn2.cross_validation.dataset_iterators.StratifiedDatasetKFold {
        dataset: !obj:pylearn2.datasets.csv_dataset.CSVDataset {
            path: '%(data_source)s',
            expect_headers: False,
            expect_labels: True,
            start: 0,
            stop: 900,
        },
        n_folds: 10,
    },

    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 100,
        nvis: 17955,
        layers: [
            !obj:pylearn2.cross_validation.mlp.PretrainedLayerCV {
                layer_name: 'h1',
                layer_content: !pkl: '%(save_pre_autoencoder_1)s',
            },
            !obj:pylearn2.cross_validation.mlp.PretrainedLayerCV {
                layer_name: 'h2',
                layer_content: !pkl: '%(save_pre_autoencoder_2)s',
            },
            !obj:pylearn2.models.mlp.Softmax {
                max_col_norm: 1.9365,
                layer_name: 'y',
                n_classes: 2,
                irange: .005,
            },
        ],
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: .05,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5,
        },
        train_iteration_mode: even_shuffled_sequential,
        monitor_iteration_mode: even_shuffled_sequential,
        cost: !obj:pylearn2.costs.mlp.Default {},
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: 50
        },
        update_callbacks: !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
            decay_factor: 1.00004,
            min_lr: .000001,
        },
    },
    extensions: [
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 250,
            final_momentum: .7,
        },
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: '%(save_mlp_best)s',
        },
    ],

    save_path: '%(save_mlp)s',
    save_freq: 1

}
