---
{
  pipeline: [
    # 'rbm-1',
    'grbm-1',
    # 'grbm-2',
    # 'grbm-3',
    'mlp',
    # 'smreg',
  ],
  config: {
    common: {
      data_source: '{data_path}/corr/corr-norm_cv_{fold}_train.csv',
      test_data_source: '{data_path}/corr/corr-norm_cv_{fold}_test.csv',
      log_file: '{log_path}/{namespace}.{step}.cv_{fold}.csv',
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      data_train_start: 0,
      data_train_stop: 900,
      data_valid_start: 900,
      data_valid_stop: 930,
      data_transform_1: '{result_path}/{namespace}.grbm-1_cv_{fold}.pkl',
      data_transform_2: '{result_path}/{namespace}.grbm-2_cv_{fold}.pkl',
      data_transform_3: '{result_path}/{namespace}.grbm-3_cv_{fold}.pkl',
    },
    rbm-1: {
      layer_in: 17955,
      layer_out: 10000,
      layer_batch: 100,
      layer_max_epochs: 100,
    },
    grbm-1: {
      layer_in: 17955,
      layer_out: 1000,
      layer_batch: 100,
      layer_max_epochs: 100,
      corruption: 0.2,
    },
    grbm-2: {
      layer_in: 1000,
      layer_out: 500,
      layer_batch: 10,
      layer_max_epochs: 55,
      corruption: 0.0,
    },
    grbm-3: {
      layer_in: 5000,
      layer_out: 500,
      layer_batch: 20,
      corruption: 0.6,
      layer_max_epochs: 600,
    },
    mlp: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 17955,
      layer_max_epochs: 100,
      layer_batch: 10,
    },
    smreg: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 500,
      layer_max_epochs: 200,
      layer_batch: 10,
    },
  }
}