---
{
  pipeline: [
    # 'AE1',
    # 'AE2',
    # 'AE3',
    # 'AE4',
    'MLP',
  ],
  config: {
    common: {
      result_path: '/home/anibal.heinsfeld/repos/acerta-abide/result-external/models',
      data_source: '{data_path}/corr/corr_cv_{fold}_train.csv',
      log_file: '{log_path}/{namespace}.{step}.cv_{fold}.csv',
      data_train_start: 0,
      data_train_stop: 880,
      data_valid_start: 880,
      data_valid_stop: 930,
      data_transform_1: '{result_path}/{namespace}.AE1_cv_{fold}.pkl',
      data_transform_2: '{result_path}/{namespace}.AE2_cv_{fold}.pkl',
      data_transform_3: '{result_path}/{namespace}.AE3_cv_{fold}.pkl',
      data_transform_4: '{result_path}/{namespace}.AE4_cv_{fold}.pkl',
    },
    AE1: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 17955,
      layer_out: 12000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 600,
      corruption: 0.3,
    },
    AE2: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 12000,
      layer_out: 7000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 600,
      corruption: 0.2,
    },
    AE3: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 7000,
      layer_out: 1000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 600,
      corruption: 0.2,
    },
    AE4: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 1000,
      layer_out: 400,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 600,
      corruption: 0.2,
    },
    MLP: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_max_epochs: 200,
      layer_batch: 10,
    },
  }
}
