---
{
  pipeline: [
    'pre-autoencoder-1-valid',
    'pre-autoencoder-2-valid',
    'pre-autoencoder-3-valid',
    'pre-autoencoder-4-valid',
    'mlp-valid',
  ],
  config: {
    common: {
      data_source: '{data_path}/corr/corr_cv_{fold}_train.csv',
      log_file: '{log_path}/{namespace}.{step}.cv_{fold}.csv',
      data_train_start: 0,
      data_train_stop: 880,
      data_valid_start: 880,
      data_valid_stop: 930,
      data_transform_1: '{result_path}/{namespace}.pre-autoencoder-1-valid_cv_{fold}.pkl',
      data_transform_2: '{result_path}/{namespace}.pre-autoencoder-2-valid_cv_{fold}.pkl',
      data_transform_2: '{result_path}/{namespace}.pre-autoencoder-3-valid_cv_{fold}.pkl',
      data_transform_2: '{result_path}/{namespace}.pre-autoencoder-4-valid_cv_{fold}.pkl',
    },
    pre-autoencoder-1-valid: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 17955,
      layer_out: 12000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 200,
      corruption: 0.2,
    },
    pre-autoencoder-2-valid: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 12000,
      layer_out: 7000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 200,
      corruption: 0.2,
    },
    pre-autoencoder-3-valid: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 7000,
      layer_out: 1000,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 200,
      corruption: 0.2,
    },
    pre-autoencoder-4-valid: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_in: 1000,
      layer_out: 400,
      layer_enc: tanh,
      layer_dec: 'null',
      layer_batch: 100,
      layer_max_epochs: 200,
      corruption: 0.2,
    },
    mlp-valid: {
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      layer_max_epochs: 100,
      layer_batch: 10,
    },
  }
}