---
{
  pipeline: [
    'ae1',
    'ae2',
    'mlp',
  ],
  config: {
    common: {
      data_source: '{data_path}/corr/corr_1D-gauss_cv_{fold}_train.csv',
      test_data_source: '{data_path}/corr/corr_1D-gauss_cv_{fold}_test.csv',
      log_file: '{log_path}/{namespace}.{step}.cv_{fold}.csv',
      save_path: '{result_path}/{namespace}.{step}_cv_{fold}.pkl',
      data_train_start: 0,
      data_train_stop: 900,
      data_valid_start: 900,
      data_valid_stop: 930,
      data_transform_1: '{result_path}/{namespace}.ae1_cv_{fold}.pkl',
      data_transform_2: '{result_path}/{namespace}.ae2_cv_{fold}.pkl',
    },
    ae1: {
      layer_in: 16836,
      layer_out: 10000,
      layer_enc: sigmoid,
      layer_dec: sigmoid,
      layer_batch: 20,
      layer_max_epochs: 600,
      corruption: 0.4,
    },
    ae2: {
      layer_in: 1000,
      layer_out: 1000,
      layer_enc: sigmoid,
      layer_dec: 'null',
      layer_batch: 10,
      layer_max_epochs: 600,
      corruption: 0.3,
    },
    mlp: {
      layer_in: 16836,
      layer_max_epochs: 200,
      layer_batch: 10,
    },
  }
}