!obj:pylearn2.train.Train {

    dataset: &train !obj:csv_dataset.CSVDataset {
        path: "/home/anibal.heinsfeld/repos/acerta-abide/data/corr/corr_train_{site}.csv",
        expect_headers: False,
        expect_labels: True,
    },

    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 10,
        nvis: 19900,
        layers: [
            !obj:pylearn2.models.mlp.PretrainedLayer {
                layer_name: "h1",
                layer_content: !pkl: /home/anibal.heinsfeld/repos/acerta-abide/data/models/first.valid.pre-autoencoder-1-valid.{site}.pkl,
            },
            !obj:pylearn2.models.mlp.PretrainedLayer {
                layer_name: "h2",
                layer_content: !pkl: /home/anibal.heinsfeld/repos/acerta-abide/data/models/first.valid.pre-autoencoder-2-valid.{site}.pkl,
            },
            !obj:pylearn2.models.mlp.Softmax {
                max_col_norm: 3.0,
                layer_name: "y",
                n_classes: 2,
                irange: 0.05,
            },
        ],
    },

    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: .0005,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .1,
        },
        train_iteration_mode: even_shuffled_sequential,
        monitor_iteration_mode: even_shuffled_sequential,
        monitoring_dataset: {
            "train": *train,
            "valid": !obj:csv_dataset.CSVDataset {
                path: "/home/anibal.heinsfeld/repos/acerta-abide/data/corr/corr_valid_{site}.csv",
                expect_headers: False,
                expect_labels: True,
            },
            "test": !obj:csv_dataset.CSVDataset {
                path: "/home/anibal.heinsfeld/repos/acerta-abide/data/corr/corr_test_{site}.csv",
                expect_headers: False,
                expect_labels: True,
            },
        },
        cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
            input_include_probs: {
                "h1": 0.6,
                "h2": 0.8,
            },
            input_scales: {
                "h1": 1.66,
                "h2": 1.25,
            },
            per_example: True,
        },
        # cost: !obj:pylearn2.costs.mlp.Default {},
        termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: 100,
        },
        # update_callbacks: !obj:pylearn2.training_algorithms.sgd.LinearDecay {
        #     start: 1,
        #     saturate: 100,
        #     decay_factor: .01,
        # },
    },

    extensions: [
        !obj:pylearn2.training_algorithms.learning_rule.MomentumAdjustor {
            start: 1,
            saturate: 100,
            final_momentum: .9,
        },
        !obj:best_params.MonitorBasedSaveBest {
            channel_name: "valid_y_misclass",
            save_path: "/home/anibal.heinsfeld/repos/acerta-abide/data/models/first.valid.mlp-valid.{site}.pkl",
        },
        !obj:csv_monitoring.CSVMonitoring {
            name: "first.valid.mlp-valid.{site}",
            file: "/home/anibal.heinsfeld/repos/acerta-abide/data/models/first.valid.mlp-valid.{site}.csv",
        },
    ],

}
