!obj:pylearn2.train.Train {

    dataset: &train !obj:csv_dataset.CSVDataset {
        path: "/home/anibal.heinsfeld/repos/acerta-abide/data/corr/corr_train_{site}.csv",
        expect_headers: False,
        expect_labels: True,
        transformers: [
            &trans1 !pkl: /home/anibal.heinsfeld/repos/acerta-abide/data/models/first.valid.pre-autoencoder-1-valid.{site}.pkl,
        ],
    },

    model: !obj:pylearn2.models.autoencoder.DenoisingAutoencoder {
        nvis: 1000,
        nhid: 600,
        irange: 0.06123724356,
        corruptor: !obj:pylearn2.corruption.BinomialCorruptor {
            corruption_level: 0.9,
        },
        act_enc: tanh,
        act_dec: null,
    },

    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate : 0.0001,
        batch_size : 10,
        monitoring_dataset: {
            "train": *train,
            "valid": !obj:csv_dataset.CSVDataset {
                path: "/home/anibal.heinsfeld/repos/acerta-abide/data/corr/corr_valid_{site}.csv",
                expect_headers: False,
                expect_labels: True,
                transformers: [
                    *trans1,
                ],
            },
            "test": !obj:csv_dataset.CSVDataset {
                path: "/home/anibal.heinsfeld/repos/acerta-abide/data/corr/corr_test_{site}.csv",
                expect_headers: False,
                expect_labels: True,
                transformers: [
                    *trans1,
                ],
            },
        },
        cost: !obj:pylearn2.costs.autoencoder.MeanSquaredReconstructionError {},
        termination_criterion : !obj:pylearn2.termination_criteria.EpochCounter {
            max_epochs: 2000,
        }
    },

    extensions: [
        !obj:best_params.MonitorBasedSaveBest {
            channel_name: "valid_objective",
            save_path: "/home/anibal.heinsfeld/repos/acerta-abide/data/models/first.valid.pre-autoencoder-2-valid.{site}.pkl",
        },
        !obj:csv_monitoring.CSVMonitoring {
            name: "first.valid.pre-autoencoder-2-valid.{site}",
            file: "/home/anibal.heinsfeld/repos/acerta-abide/data/models/first.valid.pre-autoencoder-2-valid.{site}.csv",
        },
    ],

}
